[[bond]]
source = "tpknam1qq7k2sakt4uxxnv73cd37yd38rfm6ep457pjvqgz45s5ctm7urly6gwr74t"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "60"

[bond.signatures]
tpknam1qq7k2sakt4uxxnv73cd37yd38rfm6ep457pjvqgz45s5ctm7urly6gwr74t = "signam1qrnd96llyuxagdlgth3y6rnzmkqgzcs7tg7yzw7r6zm7s7tm4xvam9t6vaqhtphfnjptzt70ncyd8kh49sdrzd7qjvxgpjyg8x08pes0c8cs4m"
